# CHANGE THESE
ATLAS_CONNECTION_STRING="YOUR_CONNECTION_STRING"
ATLAS_API_KEY="YOUR_API_KEY"
ATLAS_PROJECT_ID="YOUR_PROJECT_ID"
ATLAS_CLUSTER_NAME="YOUR_CLUSTER_NAME"
TARGET_DATABASE="TARGET_DB"
TARGET_COLLECTION="TARGET_COLLECTION"
AWS_S3_LOCATION="s3://BUCKET_NAME/FOLDER"