ATLAS_CONNECTION_STRING="ATLAS_CONNECTION_STRING"
ATLAS_CLUSTER_NAME="ATLAS_CLUSTER_NAME"
TARGET_DATABASE="TARGET_DATABASE"
TARGET_COLLECTION="TARGET_COLLECTION"
AWS_S3_LOCATION="s3://AWS_S3_LOCATION"

